import { Request, Response } from 'express';
import { sendApiResponse } from '../utils/apiResponse';
import { reportStore } from '../services/reportStore';
import { AuthenticatedRequest } from '../middlewares/auth.middleware';

export const getReports = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const reports = await reportStore.getAllReports();
    return sendApiResponse({
      res,
      statusCode: 200,
      message: 'Generated reports catalog retrieved.',
      data: reports,
    });
  } catch (error: any) {
    return sendApiResponse({
      res,
      statusCode: 500,
      success: false,
      message: 'Failed to fetch reports catalog.',
      error: { details: error.message },
    });
  }
};

export const generateReport = async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { title, reportType, format, filtersApplied } = req.body;
    const userId = req.user?.id || 'usr-analyst-01';
    const userName = req.user ? `${req.user.email} (${req.user.role})` : 'Security Analyst';

    if (!reportType || !format) {
      return sendApiResponse({
        res,
        statusCode: 400,
        success: false,
        message: 'reportType and format parameters are required.',
      });
    }

    const report = await reportStore.generateReport({
      title,
      reportType,
      format,
      filtersApplied,
      generatedById: userId,
      generatedByName: userName,
    });

    return sendApiResponse({
      res,
      statusCode: 201,
      message: 'Report compiled and generated successfully.',
      data: report,
    });
  } catch (error: any) {
    return sendApiResponse({
      res,
      statusCode: 500,
      success: false,
      message: 'Failed to generate report.',
      error: { details: error.message },
    });
  }
};

export const downloadReport = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const report = await reportStore.getReportById(id);

    if (!report) {
      return sendApiResponse({
        res,
        statusCode: 404,
        success: false,
        message: 'Report file not found.',
      });
    }

    if (report.format === 'CSV') {
      const csvData = `Report ID,Title,Report Type,Generated By,Date
"${report.id}","${report.title}","${report.reportType}","${report.generatedByName}","${report.createdAt}"
"10.45.12.89","PACS Ransomware Vector","CRITICAL","100% Contained","2026-07-24"
"10.45.3.112","EMR Brute Force SSH","HIGH","Active Investigation","2026-07-24"
`;
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="${report.id}.csv"`);
      return res.status(200).send(csvData);
    }

    return sendApiResponse({
      res,
      statusCode: 200,
      message: 'Report document payload retrieved.',
      data: report,
    });
  } catch (error: any) {
    return sendApiResponse({
      res,
      statusCode: 500,
      success: false,
      message: 'Failed to download report.',
      error: { details: error.message },
    });
  }
};

export const deleteReport = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const deleted = await reportStore.deleteReport(id);

    if (!deleted) {
      return sendApiResponse({
        res,
        statusCode: 404,
        success: false,
        message: 'Report not found.',
      });
    }

    return sendApiResponse({
      res,
      statusCode: 200,
      message: 'Report document removed from catalog.',
    });
  } catch (error: any) {
    return sendApiResponse({
      res,
      statusCode: 500,
      success: false,
      message: 'Failed to delete report.',
      error: { details: error.message },
    });
  }
};
