import { jsPDF } from 'jspdf';

export interface ExportPDFOptions {
  title?: string;
  facilityName?: string;
  reportType?: string;
  generatedBy?: string;
  metrics?: Array<{ label: string; value: string }>;
  items?: Array<{ code: string; asset: string; severity: string; status: string }>;
}

export const generateExecutiveDashboardPDF = (options?: ExportPDFOptions) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const now = new Date().toLocaleString('en-US', { timeZoneName: 'short' });
  const title = options?.title || 'AEGIS MEDSECURE • EXECUTIVE SECURITY DASHBOARD REPORT';
  const facility = options?.facilityName || 'Quaid-e-Azam International Hospital (QIH), Islamabad';
  const reportType = options?.reportType || 'EXECUTIVE SECURITY SUMMARY';
  const generatedBy = options?.generatedBy || 'Hadi Abbasi (Super Administrator)';

  // Document Color System
  const darkBg = [10, 10, 10]; // #0A0A0A
  const surfaceBg = [23, 23, 23]; // #171717
  const crimsonRed = [217, 4, 41]; // #D90429
  const textWhite = [245, 245, 245]; // #F5F5F5
  const textMuted = [160, 160, 160]; // #A0A0A0
  const emeraldGreen = [0, 200, 83]; // #00C853
  const borderGray = [42, 42, 42]; // #2A2A2A

  // Page Background Fill
  doc.setFillColor(darkBg[0], darkBg[1], darkBg[2]);
  doc.rect(0, 0, 210, 297, 'F');

  // Top Header Decorative Accent Bar
  doc.setFillColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
  doc.rect(0, 0, 210, 4, 'F');

  // Top Branding Title Bar
  doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
  doc.rect(10, 10, 190, 28, 'F');
  doc.setDrawColor(borderGray[0], borderGray[1], borderGray[2]);
  doc.rect(10, 10, 190, 28, 'S');

  // Institution Badge Label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
  doc.text('QUAID-E-AZAM INTERNATIONAL HOSPITAL • AUTONOMOUS CYBER DEFENSE', 15, 18);

  // Main Report Title
  doc.setFontSize(14);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text(title, 15, 26);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text(`Facility: ${facility} | Scope: 400+ Beds, PACS DICOM, EMR Vault`, 15, 33);

  // Report Metadata Grid Box
  doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
  doc.rect(10, 42, 190, 22, 'F');
  doc.rect(10, 42, 190, 22, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);

  doc.text('GENERATED BY:', 15, 49);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text(generatedBy, 42, 49);

  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('REPORT TYPE:', 15, 57);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text(reportType, 42, 57);

  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('TIMESTAMP:', 115, 49);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text(now, 138, 49);

  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('COMPLIANCE:', 115, 57);
  doc.setTextColor(emeraldGreen[0], emeraldGreen[1], emeraldGreen[2]);
  doc.text('HIPAA TITLE II & ISO 27001 AUDIT VERIFIED', 138, 57);

  // KPI Metrics Section Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
  doc.text('1. EXECUTIVE SECURITY METRICS MATRIX', 10, 72);

  // 4 Metric Highlight Cards
  const kpis = options?.metrics || [
    { label: 'HOSPITAL SECURITY SCORE', value: '94 / 100 (OPTIMAL)' },
    { label: 'INGESTED THREAT VECTORS', value: '42 Threats Monitored' },
    { label: 'ACTIVE SECURITY ALERTS', value: '12 Critical Pending' },
    { label: 'CONTAINMENT MTTR', value: '< 450ms Auto VLAN' },
  ];

  const colWidth = 45;
  kpis.forEach((kpi, idx) => {
    const x = 10 + idx * 47.5;
    doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
    doc.rect(x, 76, colWidth, 24, 'F');
    doc.rect(x, 76, colWidth, 24, 'S');

    doc.setFontSize(6.5);
    doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
    doc.text(kpi.label, x + 3, 82);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
    doc.text(kpi.value, x + 3, 93);
  });

  // Table Section Header
  doc.setFontSize(10);
  doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
  doc.text('2. INCIDENT & THREAT CONTAINMENT INVENTORY', 10, 110);

  // Datatable Header
  doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
  doc.rect(10, 114, 190, 8, 'F');
  doc.rect(10, 114, 190, 8, 'S');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('CODE', 14, 119);
  doc.text('TARGET ASSET & SUBNET', 45, 119);
  doc.text('SEVERITY TIER', 125, 119);
  doc.text('WORKFLOW STATUS', 165, 119);

  // Table Rows Data
  const rows = options?.items || [
    { code: 'INC-8490', asset: 'PACS DICOM Imaging Server #4 (VLAN 104)', severity: 'CRITICAL', status: 'INVESTIGATING' },
    { code: 'INC-8491', asset: 'EMR Core Patient Database Server', severity: 'CRITICAL', status: 'PENDING' },
    { code: 'INC-8492', asset: 'ICU Ventilator IoMT Gateway (10.45.3.12)', severity: 'HIGH', status: 'RESOLVED' },
    { code: 'INC-8493', asset: 'ER Central Workstation Terminal #12', severity: 'MEDIUM', status: 'RESOLVED' },
    { code: 'INC-8494', asset: 'Lab Information System (LIS) Server', severity: 'HIGH', status: 'PENDING' },
    { code: 'INC-8495', asset: 'Pharmacy Dispensing Kiosk Gateway', severity: 'LOW', status: 'RESOLVED' },
  ];

  let currentY = 126;
  rows.forEach((row) => {
    doc.setFillColor(darkBg[0], darkBg[1], darkBg[2]);
    doc.rect(10, currentY - 4, 190, 10, 'F');
    doc.setDrawColor(borderGray[0], borderGray[1], borderGray[2]);
    doc.rect(10, currentY - 4, 190, 10, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
    doc.text(row.code, 14, currentY + 2);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
    doc.text(row.asset, 45, currentY + 2);

    doc.setFont('helvetica', 'bold');
    if (row.severity === 'CRITICAL') {
      doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
    } else if (row.severity === 'HIGH') {
      doc.setTextColor(255, 179, 0); // Amber
    } else {
      doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
    }
    doc.text(row.severity, 125, currentY + 2);

    if (row.status === 'RESOLVED') {
      doc.setTextColor(emeraldGreen[0], emeraldGreen[1], emeraldGreen[2]);
    } else {
      doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
    }
    doc.text(row.status, 165, currentY + 2);

    currentY += 12;
  });

  // Section 3: AI Neural Security Insights
  doc.setFontSize(10);
  doc.setTextColor(crimsonRed[0], crimsonRed[1], crimsonRed[2]);
  doc.text('3. GPT-4o NEURAL RECOMMENDATION BRIEF', 10, currentY + 6);

  doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
  doc.rect(10, currentY + 10, 190, 24, 'F');
  doc.rect(10, currentY + 10, 190, 24, 'S');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text(
    '• Recommendation 1: Enforce zero-trust micro-segmentation on PACS DICOM Subnet #10.45.0.0/16 immediately.',
    14,
    currentY + 17
  );
  doc.text(
    '• Recommendation 2: Rotate API secret keys for automated EDR drivers and update Palo Alto PAN-OS firewall rules.',
    14,
    currentY + 23
  );
  doc.text(
    '• Recommendation 3: Execute full database integrity scan on EMR Core Patient Vault prior to shift handover.',
    14,
    currentY + 29
  );

  // Footer Governance & Digital Signature Bar
  const footerY = 265;
  doc.setFillColor(surfaceBg[0], surfaceBg[1], surfaceBg[2]);
  doc.rect(10, footerY, 190, 22, 'F');
  doc.rect(10, footerY, 190, 22, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('AUTHORIZED SIGNATURE & SOVEREIGN SEAL:', 15, footerY + 7);
  doc.setTextColor(textWhite[0], textWhite[1], textWhite[2]);
  doc.text('Hadi Abbasi — Super Administrator / Executive Boss', 15, footerY + 14);

  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text('VERIFICATION HASH:', 125, footerY + 7);
  doc.setFont('courier', 'bold');
  doc.setTextColor(emeraldGreen[0], emeraldGreen[1], emeraldGreen[2]);
  doc.text(`SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`, 125, footerY + 14);

  // Save / Trigger Real PDF File Download in User's Browser
  const fileName = `qih_aegis_executive_dashboard_report_${Date.now()}.pdf`;
  doc.save(fileName);
};
